### ISSUE TITLE
Missing URL in passwords without FIX WEBSITE tag

### ISSUE THREAD

**Issue by ghost** [gutenye/password-manager-tools#4]
I have number of passwords which came in without the FIXWEBSITE tag. The default URL field has no data at all. See that in iOS as well as macOS. 
![image](https://github.com/user-attachments/assets/9f2e7fc9-9deb-459f-95ea-6cd695f49a0d)

**Comment by gutenye** [comment]
@anuraagm0 Thank you for reporting this. Could you please provide a minimal bitwarden.json file so that I can reproduce the issue? Feel free to modify the URL and other details to protect your privacy.

**Comment by gutenye** [comment]
Please make sure you're running the latest version `1.1.0`. You can check with `bunx @gutenye/password-manager-tools version`. If it's not the latest, run it with `bunx @gutenye/password-manager-tools@1.1.0 version`

**Comment by anuraagm0** [comment]
Happy to help but not sure how to redact the data in an encrypted .json. I will export the 2-3 passwords which are behaving this way, redact the data and send it over to you.


On Oct 28, 2024, at 5:11 PM, Guten ***@***.***> wrote:

bunx @gutenye/password-manager-tools version

**Comment by gutenye** [comment]
You can construct one from [this minimal template](https://github.com/gutenye/password-manager-tools/blob/8206653a94429d7169a906b324ea4f68885184ed/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L45-L66), I suspect it's a URL issue, filling the the URLs there and test it.

**Comment by gutenye** [comment]
decrypt command is added, use `bunx @gutenye/bitwarden-password-tools decrypt input.json output.json` to decrypt it.

**Comment by gutenye** [comment]
no response
